name: tuk2
dependencies:
- python=3.5
- pip:
  - jupyter==1.0.0
  - matplotlib==2.1.0
  - https://github.com/hpi-epic/pyHANA/archive/master.zip
  - pyyaml==3.12
  - pandas==0.21
  - scikit-learn==0.19.1
  - scipy==1.0.0
  - numpy==1.13.3
